#!/bin/bash

###############################################################################
##  Author:       Adam Wright
##  Date:         5/4/2020
##  Course:       OSU cs-475
##  Project:      Project 4
##  Description:  Script to compile and run project 4 with GCC while using a
##                range of values for the #defines ARRAYSIZE and NUMT.
###############################################################################

CPP_FILE="Project_4.cpp"
EXECUTABLE="Project_4"
OUTPUT_FILE_1="Project_4_Output_SIMD.txt"
OUTPUT_FILE_2="Project_4_Output_MT_SIMD.txt"

# Clear the test file
> $OUTPUT_FILE

# Message to user while results are gathered
printf "\nGathering the results...\n"

# Enter the column values for num trials into the output file
printf "1000\t8000\t10000\t80000\t100000\t800000\t1000000\t8000000\n" >> $OUTPUT_FILE


# Iterate through the number of trials single threadedly
for s in 1000 8000 10000 80000 100000 800000 1000000 8000000
do
    # Set the number of trials
    ARRAYSIZE=$s

    # Compile and run with the currently set values and record the results
    g++ -DARRAYSIZE=$s $CPP_FILE -o $EXECUTABLE -O3 -lm -fopenmp
    ./$EXECUTABLE >> $OUTPUT_FILE
done
echo >> $OUTPUT_FILE_1


# # Iterate through the number of threads
# for t in 1 2 3 4 5 6
# do
#     # Set the number of threads
#     NUMT=$t

#     # Enter the thread count into the start of each row of the file
#     printf "$NUMT\t" >> $OUTPUT_FILE

#     # Iterate through the number of trials
#     for s in 1000 8000 10000 80000 100000 800000 1000000 8000000
#     do
#         # Set the number of trials
#         NUMTRIALS=$s

#         # Compile and run with the currently set values and record the results
#         g++ -DNUMT=$t -DNUMTRIALS=$s $CPP_FILE -o $EXECUTABLE -O3 -lm -fopenmp
#         ./$EXECUTABLE >> $OUTPUT_FILE
#     done
#     echo >> $OUTPUT_FILE_2
# done

# Print a description of the axes to the terminal
printf "\nSIMD vs non-SIMDn\n"

# Print the output file contents to the terminal
cat $OUTPUT_FILE_1
