#!/bin/bash

###############################################################################
##  Author:       Adam Wright
##  Date:         5/4/2020
##  Course:       OSU cs-475
##  Project:      Project 4
##  Description:  Script to compile and run project 4 with GCC while using a
##                range of values for the #defines ARRAYSIZE and NUMT.
###############################################################################

CPP_FILE="Project_4.cpp"
EXECUTABLE="Project_4"
OUTPUT_FILE="Project_4_Output.txt"

# Clear the test file
> $OUTPUT_FILE

# Message to user while results are gathered
printf "\nGathering the results...\n"


# Iterate through the number of threads
for t in 1 2 3 4 5 6
do
    # Set the number of threads
    NUMT=$t

    # Iterate through the different array sizes
    for s in 1000 8000 10000 80000 100000 800000 1000000 8000000
    do
        # Set the number of trials
        SIZE=$s

        # Enter the thread count and array size into each row of the output file
        printf "$NUMT\t$s\t" >> $OUTPUT_FILE

        # Compile and run with the currently set values and record the results
        g++ -DNUMT=$t -DSIZE=$s $CPP_FILE -o $EXECUTABLE -O3 -lm -fopenmp
        ./$EXECUTABLE >> $OUTPUT_FILE
    done
    echo >> $OUTPUT_FILE
done


# Print a description of the axes to the terminal
printf "\n**********************************************\n"
printf "**   Non-SIMD vs SIMD vs Multi-core SIMD    **\n"
printf "**********************************************\n\n"

printf "NUMT    SIZE         SPEEDUP1  SPEEDUP2\n\n"

# Print the output file contents to the terminal
cat $OUTPUT_FILE
