#!/bin/bash

###############################################################################
##  Author:       Adam Wright
##  Date:         4/20/2020
##  Course:       OSU cs-475
##  Project:      Project 3
##  Description:  Script to compile and run project 3 with GCC while using a
##                range of values for the #defines NUMT, NUMNODES.
###############################################################################

MAKE_FILE="makefile"
EXECUTABLE="Project_3"
OUTPUT_FILE="Project_3_Output.txt"

# Clear the test file
> $OUTPUT_FILE

# Message to user while results are gathered
printf "\nGathering the results...\n"

# Compile with makefile
mingw32-make.exe $EXECUTABLE

# Run the program and redirect stdout to file
$EXECUTABLE >>  $OUTPUT_FILE

# Print a description of the axes to the terminal
printf "\nGrain Growing Simulation\n\n"

# Print the output file contents to the terminal
cat $OUTPUT_FILE