#!/bin/bash

###############################################################################
##  Author:       Adam Wright
##  Date:         5/14/2020
##  Course:       OSU cs-475
##  Project:      Project 6
##  Description:  Script to compile and run project 6 with OpenCL while using a
##                range of values for the #defines LOCAL_SIZE, NUM.
###############################################################################

#SBATCH -J Project_6
#SBATCH -A cs475-575
#SBATCH -p class
#SBATCH --gres=gpu:1
#SBATCH -o Project_6.out
#SBATCH -e Project_6.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=wrighada@oregonstate.edu

CPP_FILE="Project_6_reduce.cpp"
EXECUTABLE="Project_6_reduce"
OUTPUT_FILE_REDUCE="Project_6_Red_Output.txt"

# Clear the test files
> $OUTPUT_FILE_REDUCE

# Message to user while results are gathered
printf "\nGathering the reduction results...\n\n"


# GATHER AND OUTPUT ARRAY MULTIPLICATION TO FILE ------------------------------
# Enter the column values for num trials into the output file
printf "        1KB\t 4KB\t 32KB\t 256KB\t 1MB\t 2MB\t 4MB\t 8MB\n" >> $OUTPUT_FILE_REDUCE

# Iterate through the number of threads per block
for t in 32 64 128 256
do
    # Set the size of the cude blocks
    LOCAL_SIZE=$t

    # Enter the thread count into the start of each row of the file
    printf "$LOCAL_SIZE\t" >> $OUTPUT_FILE_REDUCE

    # Iterate through the number of trials
    for s in 16 64 512 4096 16384 32768 65536 131072
    do
        # Set the number of trials
        NUM=$s

        # Compile and run with the currently set values and record the results
        g++ -o $EXECUTABLE $CPP_FILE -D LOCAL_SIZE=$t -D NUM=$s /usr/local/apps/cuda/cuda-10.1/lib64/libOpenCL.so.1.1 -lm -fopenmp
        ./$EXECUTABLE >> $OUTPUT_FILE_REDUCE
    done
    printf "\n" >> $OUTPUT_FILE_REDUCE
done

# Print a description of the axes to the terminal
printf "        *******************************************\n"
printf "        **        CUDA Array Reduction test      **\n"
printf "        *******************************************\n\n"
printf "           NMB(Array Size) vs. GigaMults / sec.\n\n"

# Print the multiplication file contents to the terminal
cat $OUTPUT_FILE_REDUCE
printf "\n"
